version: "3"
services:
  sc:
    image: servicecomb/service-center:1.0.0-m1
    ports:
      - "30100:30100"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
#  prom:
#    command: "--config.file=/etc/prometheus/prometheus.yml"
#    image: quay.io/prometheus/prometheus:v2.0.0
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#  grafana:
#    image: grafana/grafana
#    ports:
#      - 3000:3000
#    links:
#      - prometheus
#    depends_on:
#      - prom